- name: My first play
  hosts: kvm
  become: true
  tasks:
   - name: Smalltalk with the repos if older 1h
     register: systemupdate
     apt: 
       update_cache=yes 
       force_apt_get=yes 
       cache_valid_time=3600

