- name: Works on my machine
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - ./variables.yaml
  become: true
  gather_facts: false

  tasks:
  - name: Smalltalk with the repos if older 1h
    register: systemupdate
    apt: 
      update_cache=yes 
      force_apt_get=yes 
      cache_valid_time=3600

  - name: RBenv dependencys for ruby
    register: rubydependency
    apt:
      pkg:
      - autoconf
      - bison
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - patch
      - rustc
      - uuid-dev

  - name: Download rbenv install for ruby
    register: rbenvinstaller
    become: false     
    shell:
      cmd: curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
      warn: false

  - name: Add rbenv path to .bashrc
    register: bashrcmodify
    become: false
    ansible.builtin.blockinfile:
      path: ~/.bashrc
      backup: yes
      block: |
        export PATH="$HOME/.rbenv/bin:$PATH"
        eval "$(rbenv init -)"

  - name: Download nvm install for nodejs
    register: nvminstaller
    become: false
    shell:
      cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/"{{ nvm_installer_version }}"/install.sh | bash
      warn: false

  - name: Install latest ruby and nodejs
    register: installrubyandnodejs
    become: false
    shell: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      rbenv install "{{ ruby_version }}"
      nvm install "{{ nodejs_version }}"
      rbenv global "{{ ruby_version }}"
      nvm use "{{ nodejs_version }}"

    args:
      executable: /bin/bash

  - name: Check installation results of ruby "{{ ruby_version }}" and nodejs "{{ nodejs_version }}"
    debug:
      var: installrubyandnodejs.stdout

