- name: Works on my machine
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:

   - name: Smalltalk with the repos if older 1h
     register: systemupdate
     apt: 
       update_cache=yes 
       force_apt_get=yes 
       cache_valid_time=3600

   - name: RBenv dependencys for ruby
     register: rubydependency
     apt:
       pkg:
       - autoconf
       - bison
       - build-essential
       - libssl-dev
       - libyaml-dev
       - libreadline6-dev
       - zlib1g-dev
       - libncurses5-dev
       - libffi-dev
       - libgdbm6
       - libgdbm-dev
       - libdb-dev

   - name: Download rbenv installer script
     register: rbenvinstallerdownload
     uri:
       url: https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer
       return_content: yes

   - name: Run rbenv installer
     register: rbenvinstaller
     shell:
       cmd: sh -s -- -y
       stdin: "{{ rbenvinstallerdownload.content }}"
